### ISSUE TITLE
Archive contains editor backup files

### ISSUE THREAD

**Issue by perlpunk** [shlomif/perl-file-find-object#1]
See https://st.aticpan.org/source/SHLOMIF/File-Find-Object-0.3.3/
It contains `Changes~`, `dist.ini~` and `weaver.ini~`.

We at SUSE Linux are mirroring all CPAN modules into the Open Build System (OBS), and automatically build rpm packages.
rpm doesn't allow such files, so the build fails.
We need to update our converter script to exclude such files, but I still wanted to notify you that these files are in your tarball, and you probably didn't mean to include them.

https://build.opensuse.org/package/show/devel:languages:perl:CPAN-F/perl-File-Find-Object

**Comment by shlomif** [comment]
Thanks, should be fixed in 0.3.4.

**Comment by perlpunk** [comment]
thanks!
