### ISSUE TITLE
t/01ffo.t failure on Windows

### ISSUE THREAD

**Issue by jddurand** [shlomif/perl-file-find-object#2]
Hello,

Using perl 5.37.6 on a Windows where symlink is supported but the user do not have the privilege to use it, the mentionned test fails:

```
t/01ffo.t ............. 1/4
#   Failed test 'Avoid loop warning'
#   at t/01ffo.t line 56.
#                   undef
#     doesn't match '(?^:\AAvoid loop (\S+) => \1\S+?link\r?\n?\z)'
# Looks like you failed 1 test of 4.
```

You might want to take a look at version 1.992_01 of Test::File that export a has_symlinks that correctly reports if symlink is supported, following issue briandfoy/test-file#36 .

I have a local patched version for File::Find::Object, c.f. attachement, _but_ CPAN command refuses to upgrade to version 1.992_01 automatically. So take  care with it: the `t` patch is ok IMHO, but the dependency change in the Makefile.PL fails for me. Anyway this is giving at least an idea of the origin of the issue: testing symlink alone is not enough, as per mention in https://perldoc.perl.org/perlport#symlink .

[File-Find-Object-0.3.6-symlinks.patch](https://github.com/shlomif/perl-file-find-object/files/10327368/File-Find-Object-0.3.6-symlinks.patch)

**Comment by shlomif** [comment]
@jddurand : hi. thanks. where can I find Test::File 1.993? it's not on cpanm / metacpan.

**Comment by jddurand** [comment]
> @jddurand : hi. thanks. where can I find Test::File 1.993? it's not on cpanm / metacpan.

@shlomif it should have been on cpan, uploaded december, 31th as per @briandfoy - though you I do not see it. I'll comment on briandfoy/test-file#36

**Comment by shlomif** [comment]
@jddurand - please try v0.3.7 .

**Comment by jddurand** [comment]
Works with latest version of Test::File - many thanks.
What about adding
```
[Prereqs / TestRequires]
Test::File = 1.993

```
in dist.ini ?

**Comment by shlomif** [comment]
> Works with latest version of Test::File - many thanks. What about adding
> 
> ```
> [Prereqs / TestRequires]
> Test::File = 1.993
> ```
> 
> in dist.ini ?

no need4that - it is already detected. thanks.
